/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Define Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.DefineExpr#getVariables <em>Variables</em>}</li>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.DefineExpr#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDefineExpr()
 * @model
 * @generated
 */
public interface DefineExpr extends MathExpression, DefParenthesis
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.assingment2.mathinterpreter.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDefineExpr_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(PMExpression)
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDefineExpr_Expression()
   * @model containment="true"
   * @generated
   */
  PMExpression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.assingment2.mathinterpreter.DefineExpr#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(PMExpression value);

} // DefineExpr
